version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:9d:1b:7b:6a:98:6b:1e:46:77:49:c3:4f:0f:ff:5f"
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Prepare shell commands
          command: cp .circleci/deploy.sh ../ && chmod +x ../deploy.sh
      - run:
          name: Run deploy scripts
          command: ../deploy.sh