version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:3e:c5:38:7e:2c:d1:4a:c9:31:22:1e:95:62:27:da"
      - checkout
      - restore_cache:
          keys:
          - dependencies-
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Prepare shell commands
          command: cp .circleci/deploy.sh ../ && chmod +x ../deploy.sh
      - run:
          name: Run deploy scripts
          command: ../deploy.sh